{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "permify.fullname" . }}-job-status-reader
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "permify.fullname" . }}-job-status-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "permify.fullname" . }}-job-status-reader
subjects:
- kind: ServiceAccount
  name: {{ include "permify.serviceAccountName" . }}
{{- end }}