apiVersion: v1
kind: Service
metadata:
  name: {{ include "permify.fullname" . }}
  labels:
    {{- include "permify.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.app.server.grpc.port }}
      targetPort: grpc
      protocol: TCP

    {{- if .Values.app.server.http.enabled }}
    - name: http
      port: {{ .Values.app.server.http.port }}
      targetPort: http
      protocol: TCP
    {{- end }}

    {{- if .Values.app.profiler.enabled }}
    - name: profiler
      port: {{ .Values.app.profiler.port }}
      targetPort: profiler
      protocol: TCP
    {{- end }}

    - name: invoker
      port: {{ .Values.app.distributed.port }}
      targetPort: invoker

  selector:
    {{- include "permify.selectorLabels" . | nindent 4 }}