name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email info@permify.co

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.8.1

      - name: Add Repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add permify https://permify.github.io/helm-charts
          helm repo update

      # Update Helm Dependencies before packaging
      - name: Update Helm Dependencies
        run: |
          helm dependency update ./charts/permify

      # Package and Sign Helm Chart
      - name: Package and Sign Helm Chart
        run: |
          helm package ./charts/permify --sign --key "info@permify.co"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: .github/chart-releaser.yml
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"
          CR_SKIP_EXISTING: true
