name: Generate values schema json
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate values schema json
        uses: losisin/helm-values-schema-json-action@v2
        with:
          input: charts/permify/values.yaml
          output: charts/permify/values.schema.json
          git-push: true
          git-push-user-name: "github-actions[bot]"
          git-push-user-email: "github-actions[bot]@users.noreply.github.com"
          git-commit-message: "chore: update values schema json"
